---
- name: Get Junos facts from vMX router
  hosts: all
  connection: local
  gather_facts: yes
  tasks:
    - name: gather junos_facts
      ios_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: collect default set of facts and configuration
      ios_facts:
        gather_subset: config
