- name:	Configuration of Console password 
  hosts: cisco console password
  connection: local
  gather_facts: no
  tasks:
  
  - name: configure console password
    ios_config:
     lines:
     - line con 0
     - session-timeout 10  
     - exec-timeout 15 0
     - password S!ItH
     - stopbits 1	 
