- name:	Configuration of Aux port password  
  hosts: cisco Aux password
  connection: local
  gather_facts: no
  tasks:
  
  - name: configure Aux port password
    ios_config:
     lines:
     - line aux 0
     - session-timeout 10 
     - exec-timeout 15 0
     - password !gKdB!gU@
     - modem InOut
     - no exec
     - transport output none
     - stopbits 1
