- name:	Configuration of Line vty 0 4  password  
  hosts: cisco Line vty password
  connection: local
  gather_facts: no
  tasks:
  
  - name: configure Line vty 0 4 password
    ios_config:
     lines:
     - line vty 0 4
     - session-timeout 10 
     - access-class 12 in
     - exec-timeout 15 0
     - privilege level 15
     - password DnWt$tT!Ih
     - transport input ssh

