- name:	Configuring new access list on devices 
  hosts: cisco access list on devices 
  connection: local
  gather_facts: no
  tasks:
  
  - name: cisco access list on devices 
    ios_config:
	lines:
    access-list 83 remark *** TECH M WRITE ACCESS  ***
    access-list 83 permit 10.178.0.132 0.0.0.0
    access-list 83 permit 10.178.0.133 0.0.0..0
    access-list 83 permit 10.178.0.134 0.0.0.0
    access-list 83 permit 10.177.0.132 0.0.0.0
    access-list 83 permit 10.177.0.133 0.0.0.0
    access-list 83 permit 10.177.0.134 0.0.0.0
    access-list 83 deny any log
