- name:	Configuration of vty 5 15 password  
  hosts: cisco Line vty 5 15 password
  connection: local
  gather_facts: no
  tasks:
  
  - name: configure Line vty 5 15 password
    ios_config:
     lines:
	 - line vty 5 15
     - session-timeout 10 
     - access-class 12 in
     - exec-timeout 15 0
     - privilege level 15
     - password DnWt$tT!Ih
     - transport input ssh

